### ISSUE TITLE
user registration by only adding the email adress

### ISSUE THREAD

**Issue by Tobias-Conrad** [zanematthew/zm-ajax-login-register#117]
Email: emailadress@domain.tld
Username: emailadress
Password will be created and sent automatically

When it is so easy to register and for EU Law, we need to add double opt-in email as an option.
It also prevent dead corps in WP users.

Thanks for improve your plugin.
Ok. When it will be brought up, i could buy the premium version, too. ;-)

**Comment by zanematthew** [comment]
In the pro version there's an "email verify" setting.

**Comment by Tobias-Conrad** [comment]
so i can register only by enter email adress?

**Comment by zanematthew** [comment]
@Tobias-Conrad the user must approve themselves by using a valid email address. They still need to create a user name. The email address is not used as their user name.

However I recently added "login with email" in issue #126 support. Again, note that the user still needs to register with their username. Technically all login with email, does is a [`get_user_by( 'email' );`](https://codex.wordpress.org/Function_Reference/get_user_by) to get their login. Then logs them in.

Is this what your looking to do?

**Comment by Tobias-Conrad** [comment]
i am not technical involved. i need only add user by email adress.
all other stuff should be done by code

**Comment by zanematthew** [comment]
It is done by code. Since you are a GitHub user are already more technical than most :)

* Can users register with email: No.
* Can users login with email: Yes.

A user name is required by WordPress, and it cannot be their email address.

**Comment by Tobias-Conrad** [comment]
you can take the first part of the email adress e.g. tobias@test.de then take "test"

**Comment by zanematthew** [comment]
There's a few options I can play with like that. If this is something that
is added, it would be added in the Pro version, as I'm keeping the free
version void of all new features.

On Fri, Sep 25, 2015 at 9:23 AM, Tobias Conrad <notifications@github.com>
wrote:

> you can take the first part of the email adress e.g. tobias@test.de then
> take "test"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanematthew/zm-ajax-login-register/issues/117#issuecomment-143219948>
> .
>



-- 
Zane M. Kolnik
@zkolnik
@zanematthew

Zane Matthew
Baltimore, MD 21230
*http://zanematthew.com <http://zanematthew.com/>*
http://twitter.com/zanematthew
http://github.com/zanematthew
(443)-821-00ZM
(443)-821-0096

The contents of this e-mail and any attachments are intended solely for the
use of the named addressee(s) and may contain confidential and/or
privileged information. Any unauthorized use, copying, disclosure, or
distribution of the contents of this e-mail is strictly prohibited by the
sender and may be unlawful. If you are not the intended recipient, please
notify the sender immediately and delete this email. Thank you.
