### ISSUE TITLE
[object Object] - appended to redirect URL after login

### ISSUE THREAD

**Issue by mihche** [zanematthew/zm-ajax-login-register#140]
Hi Mate, 
After a success login the [object Object] is appended to the URL.

**Comment by mihche** [comment]
Got it !
In login.js file, after success login you have:
```javascript
ajax_login_register_show_message( $this, msg );
$this.find( form_fields ).removeAttr('disabled');
zMAjaxLoginRegister.reload( msg.redirect_url );
```
In ```ajax_login_register_show_message``` function you have:
```javascript
if ( msg.code === 'success_login' || msg.code === 'success_registration' ){
..............
zMAjaxLoginRegister.reload( form_obj )
}
```

So.. you are calling ```zMAjaxLoginRegister.reload``` passing ```form_obj```  as a parameter which is an object.
In this case the ```[object Object]```  is appended to the URL as a string, and the code 
```javascript
$this.find( form_fields ).removeAttr('disabled');
zMAjaxLoginRegister.reload( msg.redirect_url ); 
```
from the success login will never get executed

**Comment by zanematthew** [comment]
Thanks Just ran into this as well.
